export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  ASESOR = 'ASESOR',
  PICKER = 'PICKER',
}

export enum LabelStatus {
  PENDIENTE = 'PENDIENTE',
  DESPACHADA = 'DESPACHADA',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  DOWNLOAD = 'DOWNLOAD',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_RESET = 'PASSWORD_RESET',
  DEACTIVATE = 'DEACTIVATE',
}
